language: node_js
node_js:
  - "4"
  - "6"
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - npm install -g npm@^3 --cache-min 999999999
  - npm install -g coveralls --cache-min 999999999
  - time npm i -g yarn --cache-min 999999999

install:
  - yarn

script:
  - npm test
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
  - npm run compile
  - npm run filesize
  - python node_modules/travis-weigh-in/weigh_in.py ./dist/index.min.js || true # ignore size errors

# Allow Travis tests to run in containers.
sudo: false

deploy:
  provider: npm
  email: roman.zanettin@gmail.com
  api_key:
    secure: WIP
  on:
    tags: true
    node: '6'
    repo: apollostack/inferno-apollo
    branch: master
